command_timeout = 1000
add_newline = true
continuation_prompt = "▶ "
format = "[╭─$os$shell$directory$git_branch$git_commit$git_status$git_state$fill( $singularity$pijul_channel$docker_context$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust$scala$solidity$swift$terraform$typst$vlang$vagrant$zig$buf$nix_shell$conda$meson$spack$aws$gcloud$openstack$azure$nats$direnv$crystal$container)─$status$jobs$cmd_duration$username[@](white)$hostname$time$line_break╰─](bright-green)$character"

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[cmd_duration]
format = " [[took ](white)$duration](yellow)"
min_time = 1000

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
read_only = "[󰌾] "
repo_root_format = "[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style) "
repo_root_style = "bold cyan"
style = "cyan"
truncate_to_repo = true
truncation_symbol = ""
fish_style_pwd_dir_length = 1

[directory.substitutions]

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fill]
style = "bright-green"
symbol = "─"

[fossil_branch]
symbol = " "

[git_branch]
format = "[on](white) [$symbol$branch]($style) "
style = "bright-green"
symbol = " "

[git_commit]
format = "at [($hash$tag)]($style) "
style = "bold bright-green"
tag_disabled = false
tag_symbol = ""

[git_state]
am = "applying mailbox"
am_or_rebase = "applying mailbox/rebasing"
bisect = "bisecting"
cherry_pick = "cherry-picking"
format = "now [($state( $progress_current of $progress_total))]($style) "
merge = "merging"
rebase = "rebasing"
revert = "reverting"
style = "bright-magenta"

[git_status]
ahead = "⇡$count"
behind = "⇣$count"
conflicted = "=$count"
deleted = "✕$count"
diverged = "[⇣$ahead_count⇡$behind_count](yellow)"
format = "([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style) )"
modified = "!$count"
renamed = "»$count"
staged = "+$count"
stashed = "\\$$count"
style = "bright-green"
untracked = "?$count"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
format = "[$hostname]($style)"
ssh_only = false
ssh_symbol = " "
style = "yellow"

[java]
symbol = " "

[jobs]
format = " [$symbol$number]($style)"
number_threshold = 1
style = "cyan"
symbol = " "
symbol_threshold = 1

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os]
disabled = false
format = "\\[$symbol\\] "

[os.symbols]
AlmaLinux = ""
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
RedHatEnterprise = ""
Redhat = ""
Redox = "󰀘"
RockyLinux = ""
SUSE = ""
Solus = "󰠳"
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
openSUSE = ""

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
disabled = false
format = "\\[$indicator\\] "
unknown_indicator = "?sh"

[status]
disabled = false
format = " [$symbol$status]($style)"
not_executable_symbol = "󰬅"
not_found_symbol = "󰬅"
pipestatus = true
pipestatus_format = " \\[ $pipestatus\\] => [($symbol )$common_meaning$signal_name$maybe_int]($style)"
pipestatus_separator = "| "
sigint_symbol = "󰬅"
signal_symbol = "󰬅"
style = "red"
symbol = "󰬅"

[swift]
symbol = " "

[time]
disabled = false
format = " [[at ](white) $time]($style)"
style = "blue"
time_format = "%H:%M:%S"

[username]
format = " [w/ ](white)[$user]($style)"
show_always = true
style_root = "red"
style_user = "yellow"

[zig]
symbol = " "
